---
title: "enrichment"
output: html_document
date: "2023-04-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Seting analysis parameters:



# GO term enrichemnt

Loading library:
```{r}
library(goseq)
library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r}
main_folder <-  "../results/"
```


```{r}
prep_intersting_gen <- function(a, b){
  df <- read.csv(paste0( "../results/", a, b, "/", a,b, "DA_0_05_names_ref_seq.csv"))
  df <- df[df$padj<0.05,]
  df <- df[abs(df$log2FoldChange)>log2(2),]
  return(df$hgnc_symbol)
}

```


```{r}
gen12 <- prep_intersting_gen("Grupa_1", "Grupa_2")
gen13 <- prep_intersting_gen("Grupa_1", "Grupa_3")
gen23 <- prep_intersting_gen("Grupa_2", "Grupa_3")
```

```{r}
write.csv(gen12, "../results/DEG_1_2.csv",row.names=F)
write.csv(gen13, "../results/DEG_1_3.csv",row.names=F)
write.csv(gen23, "../results/DEG_2_3.csv",row.names=F)
```


Reading in data:

```{r}
go_enrichment <- function(group_1, group_2, main_folder){
  table_all <- read.csv(file = paste0(main_folder, group_1, group_2, "/", group_1, group_2, "DA_all.csv"))
  table_all <- table_all[!is.na(table_all$padj), ]
  df <- data.frame(x = table_all$X)
  df <- df %>% extract(x,"A")
  row.names(table_all) <- df$A
  genes2 <- as.integer(table_all$padj<0.05 & abs(table_all$log2FoldChange) > log2(2))
  names(genes2) = row.names(table_all)
  pwf=nullp(genes2,"hg19","ensGene")
  GO.wall=goseq(pwf,"hg19","ensGene")
  GO.wall$over_pvalue_adj <- p.adjust(GO.wall$over_represented_pvalue, method = "BH")
  GO.wall$under_pvalue_adj <- p.adjust(GO.wall$under_represented_pvalue, method = "BH")
  write.csv(GO.wall, 
          file=paste0(main_folder, group_1, group_2, "/", group_1, group_2, "go_res.csv"))
  print(paste("Liczba terimów over", sum(GO.wall$over_pvalue_adj< 0.05)))
  print(paste("Liczba terimów under", sum(GO.wall$under_pvalue_adj< 0.05)))
}
```

```{r}
go_enrichment("Grupa_1", "Grupa_2", "../results/")
```


```{r}
go_enrichment("Grupa_1", "Grupa_3", "../results/")
```



```{r}
go_enrichment("Grupa_2", "Grupa_3", "../results/")
```

```{r}
groups <- c('Grupa_1Grupa_2', 'Grupa_1Grupa_3', 'Grupa_2Grupa_3')

topPathways_all <-NULL
df_list <- list(1, 2, 3)
names(df_list) <- c('Grupa_1Grupa_2', 'Grupa_1Grupa_3', 'Grupa_2Grupa_3')


for(i in groups){
  gsea <- read.csv(paste0("../results/", i, "/", i, "go_res.csv"))
  print(head(gsea))
  gsea$catPerr <- (gsea$numDEInCat/gsea$numInCat)*100
  df_list[[i]] <- gsea
  gsea <- gsea[gsea$over_pvalue_adj < 0.05, ]
  
  topPathways <- gsea[head(order(gsea$over_pvalue_adj), n=10), 'term']

  topPathways_all <-c(topPathways_all,topPathways)
  
}

topPathways_all <- unique(topPathways_all)
```

```{r}
library(forcats)
df = NULL
df_names <- c('Grupa 1 vs 2', 'Grupa 1 vs 3', 'Grupa 2 vs 3')
for(i in groups){
  g <- df_list[[i]]

  d <- g[g$term %in% topPathways_all,]

  d$sample <- i

  df <- rbind(df,d)
}
scale = c(1e5, 1e30, 1e60)



df <- df %>%
  mutate(term = fct_reorder(term, ontology))
p <- ggplot(data=df, aes(x=sample,
             y=term,
             color=catPerr,
             size=1/over_pvalue_adj)) +
  geom_point() +
  labs(y= paste(df_names, "term"), x='', colour="Procent DEG w kategorii", size="FDR")  +
  scale_size(labels=1/scale,breaks=scale,trans = 'log10') +
  # scale_color_gradient2(low="blue", mid="white", high="red", space ="Lab" ) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), text = element_text(size = 8))

# pdf(paste0("../plots/goseq_go_terms.pdf"), useDingbats=TRUE, width = 7, height = 3.5)
# p
# dev.off()
```

## Enrricher

```{r}

plot_enricher <- function(db) {
  groups <- c('Grupa_1Grupa_2', 'Grupa_1Grupa_3', 'Grupa_2Grupa_3')

  topPathways_all <-NULL
  df_list <- list(1, 2, 3)
  names(df_list) <- c('Grupa_1Grupa_2', 'Grupa_1Grupa_3', 'Grupa_2Grupa_3')
  
  
  for(i in groups){
    gsea <- read.csv(paste0("../results/", i, "/", db, ".txt"), sep="\t")
    print(i)
    gsea <- gsea[gsea$Adjusted.P.value < 0.05, ]
    print(dim(gsea)[[1]])
    df_list[[i]] <- gsea
    topPathways <- gsea[head(order(gsea$Adjusted.P.value), n=5), 'Term']
    # 
    topPathways_all <-c(topPathways_all,topPathways)
    
  }
  
  topPathways_all <- unique(topPathways_all)
  
  df = NULL
  df_names <- c('Grupa 1 vs 2', 'Grupa 1 vs 3', 'Grupa 2 vs 3')
  for(i in groups){
    g <- df_list[[i]]
    d <- g[g$Term %in% topPathways_all,]
    print(d)
  
    d$sample <- i
  
    df <- rbind(df,d)
  }
  df[df$Term == "Transmitter-Gated Monoatomic Ion Channel Activity Involved In Regulation Of Postsynaptic Membrane Potential (GO:1904315)", "Term"] <- "term"
  scale = c(1e2, 1e3, 1e4, 1e5)
  
  p <- ggplot(data=df, aes(x=sample,
               y=Term,
               color=Combined.Score,
               size=1/Adjusted.P.value)) +
    geom_point() +
    labs(y= paste(df_names, "term"), x='', colour="Połączony wynik", size="FDR")  +
    scale_size(labels=1/scale,breaks=scale,trans = 'log10') +
    # scale_color_gradient2(low="blue", mid="white", high="red", space ="Lab" ) +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), text = element_text(size = 8))
  
  return(p)
}

```

```{r}
p <- plot_enricher("GO_Molecular_Function_2023_table")
pdf(paste0("../plots/", "GO_Molecular_Function", ".pdf"), width = 7, height = 3.5)
p
dev.off()
```

```{r}
p <- plot_enricher("GO_Cellular_Component_2023_table")
pdf(paste0("../plots/", "GO_Cellular_Component", ".pdf"), width = 7, height = 3.5)
p
dev.off()
```

```{r}
p <- plot_enricher("GO_Biological_Process_2023_table")
pdf(paste0("../plots/", "GO_Biological_Process", ".pdf"), width = 7, height = 3.5)
p
dev.off()
```

# GSEA

Setting analysis parameters:
```{r cars}
db <- "c5.go.bp.v2022.1.Hs.entrez.gmt"
db_name <- "GO_term"
```

Loading libraries:

```{r}
library(fgsea)
library(data.table)
library(ggplot2)
library(dplyr)
library(tidyr)
library(biomaRt)
library(httr)
library(ggplot2)
library(forcats)
httr::set_config(config(ssl_verifypeer = 0L))
```

Running analysis:

```{r}
rank <- read.csv(file = paste0(main_folder, folder, group_1, group_2, "DA_0_05.csv"))
rank <- rank[order(rank$log2FoldChange),] 
rank_ensembl <- rank$X



mart <- useEnsembl("ensembl","hsapiens_gene_ensembl", mirror = "useast")
G_list <- getBM(filters= "ensembl_gene_id", attributes= c("ensembl_gene_id",
                                                          "hgnc_symbol"),
                values=rank_ensembl, mart= mart)

rank_id <- as.character(G_list[match(rank_ensembl, G_list$ensembl_gene_id), 'hgnc_symbol'])
rank_id_val  <- rank$log2FoldChange
names(rank_id_val) <- rank_id
rank_id_val <- rank_id_val[!is.na(names(rank_id_val))]
rank_id_val <- rank_id_val[!duplicated(names(rank_id_val))]

gmt.file <- system.file("extdata", db, package="fgsea")
pathways <- gmtPathways(gmt.file)

print(head(rank_id_val))
print(tail(rank_id_val))
fgseaRes <- fgsea(pathways, rank_id_val, maxSize=500)
fgseaRes <- fgseaRes[order(padj), ]
fwrite(fgseaRes, file=paste0(main_folder, folder, group_1, group_2, "_", db_name ,"_GSEA.csv"), sep=",", sep2=c("", " ", ""))
```

Choosing significant terms:

```{r}
db_name <- 'tft'
db_name_plot <- 'TFT'
db_name <- 'reactome'
db_name_plot <- 'Reactome'
# db_name <- 'kegg'
# db_name_plot <- 'KEGG'
# db_name <- 'go'
# db_name_plot <- 'GO'
# go_type<- "GOMF"  #GOCC, GOBP, GOMF

groups <- c('Grupa_1Grupa_2', 'Grupa_1Grupa_3', 'Grupa_2Grupa_3')

topPathways_all <-NULL
df_list <- list(1, 2, 3)
names(df_list) <- c('Grupa_1Grupa_2', 'Grupa_1Grupa_3', 'Grupa_2Grupa_3')


for(i in groups){
  gsea <- read.csv(paste0(main_folder, i, "/" , i, "_", db_name ,
                            "_GSEA_hgnc.csv"))
  # gsea <- gsea %>% filter(grepl(go_type, pathway))
  df_list[[i]] <- gsea
  gsea <- gsea[gsea$padj < 0.05, ]
  print(dim(gsea))
  topPathways <- gsea[head(order(gsea$padj), n=5), 'pathway']
  topPathways_all <-c(topPathways_all,topPathways)
  
}

topPathways_all
```

Making a plot of results:

```{r}
library(forcats)
df = NULL
df_names <- c('Grupa 1 vs 2', 'Grupa 1 vs 3', 'Grupa 2 vs 3')
for(i in groups){
  g <- df_list[[i]]

  d <- g[g$pathway %in% topPathways_all,]

  d$sample <- i

  df <- rbind(df,d)
}
scale = c(1, 10, 100, 1000, 10000)



df <- df %>%
  mutate(pathway = fct_reorder(pathway, NES))
p <- ggplot(data=df, aes(x=sample,
             y=pathway,
             colour=NES,
             size=1/padj)) +
  geom_point() +
  labs(y= paste(db_name_plot, "term"), x='', colour="NES", size="FDR")  +
  scale_size(labels=1/scale,breaks=scale,trans = 'log10') +
  scale_color_gradient2(low="blue", mid="white", high="red", space ="Lab" ) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), text = element_text(size = 8))

pdf(paste0("../plots/gsea_", db_name, "_", go_type, ".pdf"), useDingbats=TRUE, width =7, height = 3.5)
p
dev.off()

```

