---
title: "marker_genes"
output: html_document
date: "2023-04-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading libraries:

```{r message=FALSE}
library(MGFR)
library(DESeq2)
library(ggpubr)
library(ROCR)
library(ggplot2)
library(ggrepel)
library("tidyr")
```

```{r}
simp_ensemble <- function(col){
  df <- data.frame(x = col)
  df <- df %>% extract(x,"A")
  return(df$A)
}
```


Reading in data:

```{r}
load(file = '../results/dds_design.RData')
rna <- counts(dds, normalized = T)
pasAnno <- "../data/id_info_rna_klaster.csv"
coldata <- read.csv(pasAnno)
row.names(rna) <- simp_ensemble(row.names(rna))
```

```{r}
classes <- coldata[match(colnames(rna), coldata$samp_id), "Cluster"]
```

Looking for Marker genes:

```{r}
markers.list <- getMarkerGenes.rnaseq(rna, class.vec = classes, annotate =T)
```

```{r}
markers.list[["Cluster_1_markers"]]
markers.list[["Cluster_2_markers"]]
markers.list[["Cluster_3_markers"]]
```


```{r}
library(scran)
```

```{r}
library(biomaRt)
mart <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
```





Using AUC analysis to find marker genes:

```{r}
library(ROCR)
calc_auc <- function(x, g) {
  test_class <- numeric(length(x))
  test_class[classes == g] <- 1
  pred_object <- prediction(x, test_class)
  auc.perf = performance(pred_object, measure = "auc")
  return(auc.perf@y.values[[1]][1])
}
```

```{r}
x <- rna['ENSG00000100934', ]
g <- 'Cluster_3'
test_class <- numeric(length(x))
test_class[classes == g] <- 1
pred <- prediction(x, test_class)
perf <- performance(pred, "tpr", "fpr")
auc1 <- performance(pred, measure = "auc")@y.values[[1]]
rd <- data.frame(x = perf@x.values[[1]], y = perf@y.values[[1]])
p1 <- ggplot(rd, aes(x = x, y = y)) + geom_path(size = 1) +
  geom_text(
    aes(
      x = 0.5,
      y = 0.25,
      hjust = 0.1,
      vjust = 0,
      label = paste(sep = "", "AUC = ", round(auc1, 3))
    ),
    colour = "black",
    size = 4
  ) +
  scale_x_continuous(name = "FPR") +
  scale_y_continuous(name = "TPR") + ggtitle("SEC23A") + theme(axis.text.x = element_text(
    angle = 45,
    vjust = 1,
    hjust = 1
  ),
  text = element_text(size = 8))
```

```{r}
library(ROCR)
x <- rna['ENSG00000118971', ]
g <- 'Cluster_3'
test_class <- numeric(length(x))
test_class[classes != g] <- 1
pred <- prediction(x, test_class)
perf <- performance(pred, "tpr", "fpr")
auc2 <- performance(pred, measure = "auc")@y.values[[1]]
rd <- data.frame(x = perf@x.values[[1]], y = perf@y.values[[1]])
p2 <- ggplot(rd, aes(x = x, y = y)) + geom_path(size = 1) +
  geom_text(
    aes(
      x = 0.5,
      y = 0.25,
      hjust = 0.1,
      vjust = 0,
      label = paste(sep = "", "AUC = ", round(auc2, 3))
    ),
    colour = "black",
    size = 4
  ) + scale_x_continuous(name = "FPR") + scale_y_continuous(name = "TPR") + ggtitle("CCND2") + theme(axis.text.x = element_text(
    angle = 45,
    vjust = 1,
    hjust = 1
  ),
  text = element_text(size = 8))
```

```{r}
x <- rna['ENSG00000136931',]
g <- 'Cluster_1'
test_class <- numeric(length(x))
test_class[classes == g] <- 1
pred <- prediction(x, test_class)
perf <- performance(pred, "tpr", "fpr")
auc3 <- performance(pred, measure = "auc")@y.values[[1]]
rd <- data.frame(x = perf@x.values[[1]], y = perf@y.values[[1]])
p3 <- ggplot(rd, aes(x = x, y = y)) + geom_path(size = 1) +
  geom_text(
    aes(
      x = 0.5,
      y = 0.25,
      hjust = 0.1,
      vjust = 0,
      label = paste(sep = "", "AUC = ", round(auc3, 3))
    ),
    colour = "black",
    size = 4
  ) + scale_x_continuous(name = "FPR") + scale_y_continuous(name = "TPR") + ggtitle("NR5A1") + theme(axis.text.x = element_text(
    angle = 45,
    vjust = 1,
    hjust = 1
  ),
  text = element_text(size = 8))

```

```{r}
p <- ggarrange(p1, p2, p3, nrow = 1,  labels = c("A", "B", "C"))
grDevices::cairo_pdf(file = "../plots/roc_marker.pdf", height = 3)
p
dev.off()
```


```{r}
g = 'Cluster_3'
auc_l <- apply(rna, 1, calc_auc, g = g)
g = 'Cluster_1'
auc_p <- apply(rna, 1, calc_auc, g = g)
g = 'Cluster_2'
auc_h <- apply(rna, 1, calc_auc, g = g)
combine <-
  data.frame(
    'ensembl' = row.names(rna),
    'auc_2' = auc_h,
    'auc_1' = auc_p,
    'auc_3' = auc_l
  )
```

```{r}

G_list <- getBM(filters= "ensembl_gene_id", attributes= c("ensembl_gene_id",
                                                          "hgnc_symbol"),
                values=rownames(combine), mart= mart)
```

```{r}
combine$hgnc <- G_list[match(combine$ensembl, G_list$ensembl_gene_id), "hgnc_symbol"]
```

```{r}
write.csv(combine, file="../results/roc_deseq_norm.csv")
```


```{r}
marker_auc <- read.csv("../results/roc_deseq_norm.csv")
```

```{r}
best_auc_plot <- function(col, tit) {
  marker_auc_1 <-
    marker_auc[order(marker_auc[,col], decreasing = TRUE), c("hgnc", col)]
  colnames(marker_auc_1) <- c("hgnc", "auc")
  marker_auc_1 <- marker_auc_1[marker_auc_1$auc >0.99,]
  marker_auc_1 = marker_auc_1[!duplicated(marker_auc_1$hgnc), ]
  marker_auc_1$hgnc <-
    factor(marker_auc_1$hgnc, levels = marker_auc_1$hgnc)
  print(dim(marker_auc_1)[[1]])
  p <- ggplot(marker_auc_1, aes(x = hgnc, y = auc)) +
    theme_classic() +
    geom_point(size=0.5)   +
    labs(title = tit,
       x = "Geny",
       y = "AUC")  +
     scale_y_continuous(breaks = seq(0.99, 1.1, by =0.0025) )+
  ylim(0.99, 1)+
    # geom_text_repel(
    #   data = marker_auc_1[marker_auc_1$auc==1,],
    #   aes(label = hgnc),
    #   size = 2,
    #   max.overlaps = 20
    # ) +
    theme(
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      text = element_text(size = 8)
    ) 
  p
}

```

```{r}
p1 <- best_auc_plot("auc_1", "Grupa 1")
p2 <- best_auc_plot("auc_2", "Grupa 2")
p3 <- best_auc_plot("auc_3", "Grupa 3")
```

```{r}
p <- ggarrange(p1, p2, p3, nrow = 1,  labels = c("A", "B", "C"))
pdf(file = "../plots/best_auc.pdf", height = 2.5)
p
dev.off()
```


```{r}
library(plotly)
classes_pl <- classes
classes_pl[classes_pl=="Cluster_1"] <- "Grupa 1"
classes_pl[classes_pl=="Cluster_2"] <- "Grupa 2"
classes_pl[classes_pl=="Cluster_3"] <- "Grupa 3"
markers <- data.frame(NR5A1=rna['ENSG00000136931', ], EEIG1=rna['ENSG00000167106', ], ARHGEF10L=rna['ENSG00000074964',], cluster=classes_pl)
fig <- plot_ly(data = markers, x = ~EEIG1, y = ~ARHGEF10L, z = ~NR5A1, color=~cluster, type="scatter3d")

fig

```


