---
title: "microenvironment"
output: html_document
date: "2023-04-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Lading libraries: 

```{r}
library(immunedeconv)
library(biomaRt)
library(dplyr)
library(tidyr)
library(ggplot2)
library(reshape2)
```

Reading in data:

```{r}
load(file = '../data/dds.RData')
rna_org <- counts(dds, normalized = T)
pasAnno <- "../data/id_info_rna_klaster.csv"
coldata <- read.csv(pasAnno)
rna <- read.csv('../data/ALL_TPM.csv')
rna <- rna[rna$Gene_Id %in% row.names(rna_org),]
```


```{r}
row.names(rna) <- simp_ensemble(rna$Gene_Id)
rna <- rna[ , -which(names(rna) %in% c('Gene_Id'))]
```


```{r}

library(httr)
httr::set_config(config(ssl_verifypeer = 0L))
mart <- useEnsembl("ensembl","hsapiens_gene_ensembl", mirror = "useast")
genes_hgnc <- getBM(attributes= c("ensembl_gene_id","hgnc_symbol"), mart= mart)
``` 


```{r}
rna_m <- as.matrix(rna)
row.names(rna_m) <- genes_hgnc[match(row.names(rna_m), genes_hgnc$ensembl_gene_id), "hgnc_symbol"]
rna_m <- rowsum(rna_m, row.names(rna_m))
```

Running analysis:

```{r}
res = deconvolute(rna_m, "epic")
colnames(res) <- sub("X", "", colnames(res))
```

Saving results as plot:

```{r}
epic_df <- read.csv('../results/epic_res_p_val.csv')
colnames(epic_df)<-gsub("X","",colnames(epic_df))
epic_df <- epic_df[,c('cell_type',coldata$samp_id)]
# epic_df <- epic_df[1:7,]
epic_df <- melt(epic_df)
colnames(epic_df) <- c('cell_type', 'samp_id', 'value')
epic_df$cell_type <- factor(epic_df$cell_type, levels = c("B cell", "T cell CD4+","T cell CD8+", "Endothelial cell",  "Macrophage","Cancer associated fibroblast","NK cell", "uncharacterized cell" ))
epic_df <- merge(epic_df, coldata, by='samp_id')
colnames(epic_df)[colnames(epic_df) == 'artykul'] <- 'Cluster'
epic_df$value <- epic_df$value*100
```

```{r}
p <- ggplot(epic_df, aes(x=Cluster, y=value, fill=Cluster)) + 
  geom_violin()+ geom_dotplot(binaxis='y', stackdir='center', dotsize=1, fill = "black", alpha=0.5)+
  theme_classic() + theme(legend.position="bottom", text = element_text(size = 8), aspect.ratio=1) +
  facet_wrap(~cell_type, scales = "free")
pdf("../plots/immuno.pdf")
p
dev.off()
```




```{r}
cell_type_p_val <- epic_df[,c(51:58)]
row.names(cell_type_p_val) <- epic_df$cell_type

```

